# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 544)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 161, 121))
        self.groupBox.setObjectName("groupBox")
        self.loginSSH = QtWidgets.QLineEdit(self.groupBox)
        self.loginSSH.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.loginSSH.setObjectName("loginSSH")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label_2.setObjectName("label_2")
        self.domainSSH = QtWidgets.QLineEdit(self.groupBox)
        self.domainSSH.setGeometry(QtCore.QRect(60, 40, 91, 20))
        self.domainSSH.setObjectName("domainSSH")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_3.setObjectName("label_3")
        self.passwordSSH = QtWidgets.QLineEdit(self.groupBox)
        self.passwordSSH.setGeometry(QtCore.QRect(60, 60, 91, 20))
        self.passwordSSH.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordSSH.setObjectName("passwordSSH")
        self.connectButton = QtWidgets.QPushButton(self.groupBox)
        self.connectButton.setGeometry(QtCore.QRect(60, 90, 91, 23))
        self.connectButton.setObjectName("connectButton")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 130, 381, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.outputWindow = QtWidgets.QTextBrowser(Dialog)
        self.outputWindow.setGeometry(QtCore.QRect(10, 150, 256, 192))
        self.outputWindow.setObjectName("outputWindow")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Аутентификация"))
        self.label.setText(_translate("Dialog", "Логин:"))
        self.label_2.setText(_translate("Dialog", "Домен:"))
        self.label_3.setText(_translate("Dialog", "Пароль:"))
        self.connectButton.setText(_translate("Dialog", "Подключиться"))
