# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1340, 860)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(-1, -1, 1341, 861))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.loginSSH = QtWidgets.QLineEdit(self.groupBox)
        self.loginSSH.setObjectName("loginSSH")
        self.gridLayout.addWidget(self.loginSSH, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.domainSSH = QtWidgets.QLineEdit(self.groupBox)
        self.domainSSH.setObjectName("domainSSH")
        self.gridLayout.addWidget(self.domainSSH, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.passwordSSH = QtWidgets.QLineEdit(self.groupBox)
        self.passwordSSH.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordSSH.setObjectName("passwordSSH")
        self.gridLayout.addWidget(self.passwordSSH, 1, 1, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.groupBox)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.numberSSH = QtWidgets.QLineEdit(self.groupBox_2)
        self.numberSSH.setObjectName("numberSSH")
        self.gridLayout_3.addWidget(self.numberSSH, 0, 0, 1, 1)
        self.foundID = QtWidgets.QPushButton(self.groupBox_2)
        self.foundID.setObjectName("foundID")
        self.gridLayout_3.addWidget(self.foundID, 2, 0, 1, 1)
        self.foundDomainSSH = QtWidgets.QLineEdit(self.groupBox_2)
        self.foundDomainSSH.setObjectName("foundDomainSSH")
        self.gridLayout_3.addWidget(self.foundDomainSSH, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.shortID = QtWidgets.QLineEdit(self.groupBox_4)
        self.shortID.setObjectName("shortID")
        self.gridLayout_4.addWidget(self.shortID, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.outputWindow = QtWidgets.QTextBrowser(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.outputWindow.setFont(font)
        self.outputWindow.setMouseTracking(True)
        self.outputWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.outputWindow.setAutoFillBackground(False)
        self.outputWindow.setObjectName("outputWindow")
        self.verticalLayout.addWidget(self.outputWindow)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Логи звонка из Eltex"))
        self.groupBox.setTitle(_translate("Dialog", "Аутентификация"))
        self.label.setText(_translate("Dialog", "Логин:"))
        self.label_2.setText(_translate("Dialog", "Домен:"))
        self.domainSSH.setText(_translate("Dialog", "ssw.gravitel.ru"))
        self.label_3.setText(_translate("Dialog", "Пароль:"))
        self.connectButton.setText(_translate("Dialog", "Подключиться"))
        self.groupBox_2.setTitle(_translate("Dialog", "Поиск Short ID"))
        self.numberSSH.setText(_translate("Dialog", "номер"))
        self.foundID.setText(_translate("Dialog", "Найти ID"))
        self.foundDomainSSH.setText(_translate("Dialog", "gravitel.aicall.ru"))
        self.groupBox_4.setTitle(_translate("Dialog", "Введите Short ID"))
        self.pushButton.setText(_translate("Dialog", "Найти лог"))
        self.outputWindow.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\';\"><br /></p></body></html>"))
